### PR TITLE
non-generic local storage access

### PR DESCRIPTION
**Pull request by RonSijm**
Intention: Use local storage in combination with Fluxor to create auto-state recovery for features:

Middleware:

    using Blazor.Fluxor;
    using Blazored.LocalStorage;
    
    namespace RonSijm
    {
        public class RestoreStateMiddleware : Middleware
        {
            private readonly ISyncLocalStorageService _syncLocalStorageService;
    
            public RestoreStateMiddleware(ISyncLocalStorageService syncLocalStorageService)
            {
                _syncLocalStorageService = syncLocalStorageService;
            }
    
            public override void AfterInitializeAllMiddlewares()
            {
                foreach (var storeFeature in Store.Features)
                {
                    var name = storeFeature.Value.GetName();
                    var type = storeFeature.Value.GetStateType();
                    var item = _syncLocalStorageService.GetItem(name, type);
    
                    if (item == null)
                    {
                        continue;
                    }
    
                    storeFeature.Value.RestoreState(item);
                }
    
                base.AfterInitializeAllMiddlewares();
            }
        }
    }

### CODE REVIEW

**Comment by chrissainty** [comment]
Hi @RonSijm, looking at your code I have a couple of some concerns/questions.

Are you are planning on using this with Blazor WebAssembly only?
If so middleware doesn't exist in blazor Wasm. 

If not, then the above could wouldn't work as you have to access local storage using async APIs from Blazor Server.

**Comment by RonSijm** [comment]
Hey @chrissainty - thanks for mentioning the concerns. This isn't a normal Blazor Middleware, it's a middleware of `Blazor.Fluxor.Middleware` - I made a 'counter example' based on the default counter, the above middleware and the syncLocalStorageService, and that seemed to work. (I can share the sample if you're interested, but I planned to make a seperate post somewhere since the `Blazor.Fluxor.Middleware` is very unrelated to this project :) )

The sample above was mainly to illustrate what I was trying to solve, main important line is this one:

`var item = _syncLocalStorageService.GetItem(name, type);`

Getting an item without a generic parameter would be useful in other contexts as well

**Comment by chrissainty** [comment]
Thanks for the clarification @RonSijm. Yes, I don't see why we can't get this feature added in. You'll need to update your work based on some recent changes that are now in master. Once that's done I'd be happy to merge.

**Comment by chrissainty** [comment]
@RonSijm Hey, just wondering if you still want this work merged? Not heard back after my last comment.

**Comment by chrissainty** [comment]
As this PR is outdated and there has been no response to comments I'm going to close it.

**Pull request closed without merging**
