### PR TITLE
Updated csproj

### PR DESCRIPTION
**Pull request by MarkStega**

### CODE REVIEW

**Comment by chrissainty** [comment]
Thanks for this Mark, I’ve been keeping up with the issue you raised. I’ll take a proper look at this in the morning.

**Comment by MarkStega** [comment]
It works for @SQL-MisterMagoo so I hopew we are good to go now. There was also a suggestion in the issue to move the TS file out of wwwroot to avoid packaging it as a resource. I don't know how to redirect the TSC output so I didn't tackle that. The TS is so tiny it probably doesn't matter...

**Comment by chrissainty** [comment]
Yes, I saw the note about the TS file. In hindsight I don’t know why I put it there in the first place. I’ll move it out to somewhere more appropriate.

**Comment by chrissainty** [comment]
I’ve just pushed an update to master which moved the blazored-localstorage.ts file out of the wwwroot. Just need to check it all goes through the build ok.

**Comment by MarkStega** [comment]
Chris,

I just synced my local repository to this master. On my system the JS is now getting output to the Interop folder, not the wwwroot folder. So there is no wwwroot directory and no js in the dll. I am not familiar enough with tsconfig.json to know what the issue is...

**Comment by chrissainty** [comment]
I ran this through builds on Azure DevOps several times last night and the
JS and wwwroot folder was created as expected every time. Check that the
tsconfig.json has an outdir set to wwwroot.

**Comment by MarkStega** [comment]
The tsconfig looks correct to me. Is there a switch needed to enable use of the tsconfig?

`
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": true,
    "sourceMap": true,
    "target": "es6",
    "outDir": "wwwroot"
  },
  "exclude": [
    "wwwroot"
  ]
}
`

**Comment by MarkStega** [comment]
Here is my VS windows after a build. Notice no wwwroot & JS in the interop directory

**Comment by MarkStega** [comment]
As far as I can determine the tsconfig.json is only used from the command line invocation of TSC.
I believe that you have to add
`
  <PropertyGroup>
    <TypeScriptOutDir>wwwroot</TypeScriptOutDir>
  </PropertyGroup>
`
with that added, the good news is that the wwwroot directory gets created with the JS output of TSC within. The bad news is that fancy ResolveStaticWebAssetsInputsDependsOn doesn't work and we are again missing the JS in the DLL.

**Pull request merged**
