### PR TITLE
Converts to .NET 5.0

### PR DESCRIPTION
**Pull request by ocdsoft**
I created this because 3.0.0 wasn't working for me in a 5.0 project, but it must have been something else because it's working fine now.  However, 5.0 is the default template for projects in VS 2019 so I'm sure you would be moving there at some point.  This PR will save you about an hour when you do.

### CODE REVIEW

**Comment by SimonCropp** [comment]
@chrissainty can i help with this one?

**Comment by chrissainty** [comment]
@SimonCropp No, I don't think so. Right now I don't want to move the library to .NET 5. There are no great benefits for this library and a lot of people are sticking with .NET Core 3.x as its LTS

**Comment by SimonCropp** [comment]
just me... but i would have let those people stay on the older version of your library

**Comment by chrissainty** [comment]
If there was a reason to move the library along to the newer version I would. But currently there isn't. I appreciate your input but things will stay as is for the moment.

**Comment by SimonCropp** [comment]
yep no worries 😉

**Comment by ocdsoft** [comment]
Can bug #115 be fixed without moving to .NET 5?  If not, that would be a reason to move the library along.

**Comment by Kim-SSi** [comment]
Would it be a good idea to support both with TargetFrameworks? That way people that want the fix can use the newer net5.0 library.

**Comment by stephulk** [comment]
Is there a plan to update this to .NET 5.x? Is the code still being supported?

**Comment by chrissainty** [comment]
Closing in favour of #132

**Pull request closed without merging**
