### PR TITLE
Include support to enumerate storage keys

### PR DESCRIPTION
**Pull request by jan-johansson-mr**
Hi @chrissainty,
Please review.
This update introduces support to enumerate keys in local storage, and with updated readme.
Thanks,
//Jan

### CODE REVIEW

**Comment by jan-johansson-mr** [comment]
Hi @chrissainty,

A friendly reminder :-)

**Comment by jan-johansson-mr** [comment]
Hi there @chrissainty,

I've introduced feature of enumerate items (race condition aware), please have a look.

Thanks

**Comment by chrissainty** [comment]
Hi, @jan-johansson-mr 
I'm just having a play with the PR. I want to be upfront about this, I've not looked at or tried the async streaming stuff at all, but it seems really hard to work with. I've tried to add a method to the index page in one of the sample apps to return the keys from storage -- I can't get it to compile for love nor money. Here's what I wrote.

```
async string GetKeys()
{
    await foreach (var key in sessionStorage.GetKeysAsync())
    {
        yield return key;
    }
}
```

Could you add an example of using this as a method call, if it doesn't help anyone else it would help me.

**Comment by chrissainty** [comment]
Hi @jan-johansson-mr 
I've been trying out the new feature and I want to stress here, I've not done anything with the new async streams stuff. But its seems really difficult to use. I've been trying for the past 15 minutes to list out the keys from storage and I can't do it for love nor money. It seems razor doesn't support `await foreach` which makes using the feature from component mark up impossible at the moment.

I've also tried adding the keys to a list from the code block and print that out but I can't get that to work either. Can you add an example to the sample project showing how this can be used outside of the event-based sample?

I'm sure this is just my lack of knowledge but if I'm hitting these problems I'm sure others will too.

**Comment by jan-johansson-mr** [comment]
Hi @chrissainty,

Absolutely! This stuff simply has to work as expected, and no one should face any issues. Let me do some work, and then add to my repo so you can try.

Sorry for the problems!

**Comment by jan-johansson-mr** [comment]
Hi @chrissainty,

I've updated with samples, and also the readme file for some more information.
It really works good, but then again, as you discovered, when and where to use `await` may cause confusion. I tried to write some about it in the readme. I leave it to you to decide if this PR is a candidate :-)

As a side note, I discovered a bug in the code (referring to session storage where it should refer to local storage) that also might have added to the problems. I fixed it!

Thanks

**Comment by chrissainty** [comment]
@jan-johansson-mr My apologies for another long delay. I've been churning this over trying to decide what to do. My gut feeling is that razor isn't quite ready for the async streaming stuff just yet. I'm really grateful for the work work you've put in but I'm not sure this is the right time to add this feature.

**Comment by jan-johansson-mr** [comment]
@chrissainty No problems :-)

In honest, I don't think Blazor (or actually Razor) will ever be ready for streaming, simply because the main responsibility of Razor is to render the UI, not to process backend streaming of data to client (that is done synchronously by the render pipeline and not synchronously). Please do not feel bad dropping the PR. I agree, usage of streaming to storage is way ambitious. It's much easier to simply enumerate from the storage to pick up whatever keys we have, and by using already present primitives (Length and Key) in Blazored will more than do the trick.

Thanks for good feedback!

**Comment by chrissainty** [comment]
Thanks for being so understanding @jan-johansson-mr. I'll go ahead and close this PR and the one on Session Storage. Once again, thank you for your awesome work.

**Pull request closed without merging**
